wm_scheme:
  name: wm_noise
  num_classes: 1000
  std: 0.4

embed:
  name: wm_noise_embed
  source_class: 4
  target_class: 6
  epochs: 5
  keylength: 100
  patience: 5
  decrease_lr_factor: 1
  boost_factor: 1000

source_model:
  name: imagenet_resnet
  image_size: 224
  num_classes: 1000

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5.e-4
  momentum: 0.9
  nesterov: true

wm_dataset:
  name: ImageNetDataLoader
  apply_normalization: False
  apply_augmentation: False
  class_labels: 4
  train: True
  subset: defender
  root: ~/.wrt/data
  n_train: 1000
  n_test: 5000
  batch_size: 64
  image_size: 224
  num_workers: 16

dataset:
  name: ImageNetDataLoader
  subset: defender
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16

name: noise
output_dir: outputs/imagenet/wm/noise/


