wm_scheme:
  name: wm_dawn
  rate: 0.05
  num_classes: 10

embed:
  name: wm_dawn_embed
  epochs: 60
  keylength: 100

source_model:
  name: cifar_wide_resnet_features
  image_size: 32
  num_classes: 10

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5.e-4
  momentum: 0.9
  nesterov: true

scheduler:
  name: MultiStepLR
  milestones: [20, 35, 50]
  gamma: 0.2

surrogate_model:
  name: cifar_wide_resnet_features
  image_size: 32
  num_classes: 10

surrogate_optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5.e-4
  momentum: 0.9
  nesterov: true

dataset:
  name: CIFAR10DataLoader
  subset: all
  root: ~/.wrt/data
  batch_size: 64
  image_size: 32
  num_workers: 16

name: dawn
output_dir: outputs/cifar10/wm/dawn